<?php
ini_set('display_errors','0');define('WP_USE_THEMES',false);ob_start();require '/var/www/html/wp-load.php';ob_end_clean();
function ng_fail($s){throw new RuntimeException($s);}
function ng_state($id){$p=get_post($id);if(!$p||$p->post_type!=='product')ng_fail('Product');$meta=get_post_meta($id);unset($meta['_yoast_wpseo_title'],$meta['_yoast_wpseo_metadesc']);return ['id'=>$id,'content'=>$p->post_content,'h1'=>$p->post_title,'excerpt'=>$p->post_excerpt,'url'=>get_permalink($id),'gallery'=>get_post_meta($id,'_product_image_gallery',true),'seo_title'=>get_post_meta($id,'_yoast_wpseo_title',true),'meta_description'=>get_post_meta($id,'_yoast_wpseo_metadesc',true),'protected_meta_hash'=>hash('sha256',serialize($meta)),'shared_block_hash'=>hash('sha256',get_post(9586)->post_content)];}
function ng_stable($a,$b){foreach(['h1','excerpt','url','gallery','protected_meta_hash','shared_block_hash'] as $k)if($a[$k]!==$b[$k])ng_fail('Protected drift '.$a['id'].' '.$k);}
function ng_refresh($id){clean_post_cache($id);wp_cache_delete($id,'post_meta');if(function_exists('YoastSEO')&&class_exists('Yoast\\WP\\SEO\\Builders\\Indexable_Builder'))YoastSEO()->classes->get('Yoast\\WP\\SEO\\Builders\\Indexable_Builder')->build_for_id_and_type($id,'post');$url=get_permalink($id);if(function_exists('rocket_clean_files'))rocket_clean_files([$url]);do_action('litespeed_purge_url',$url);}
try{
 if(PHP_SAPI!=='cli'||rtrim(home_url(),'/')!=='https://shustrik-maps.com')ng_fail('Site');$mode=$argv[1]??'--preview';if(!in_array($mode,['--preview','--apply','--verify','--rollback-preview','--rollback']))ng_fail('Mode');
 $manifest=json_decode(file_get_contents(__DIR__.'/manifest.json'),true,512,JSON_THROW_ON_ERROR);$targets=$manifest['rows'];$assets=json_decode(file_get_contents(__DIR__.'/media.json'),true,512,JSON_THROW_ON_ERROR);if(array_column($targets,'id')!==[9405,9467,9468,9473,9407]||count($assets)!==20)ng_fail('Scope');foreach($assets as $m)if(hash_file('sha256',__DIR__.'/'.$m['file'])!==$m['sha256'])ng_fail('Asset hash');$out=[];
 foreach($targets as $t){$id=$t['id'];$key='_shustrik_five_country_stl_slider_backup_20261006_'.$id;$backup=get_option($key,null);$now=ng_state($id);$selected=array_values(array_filter($assets,function($m)use($id){return $m['product_id']===$id;}));if(count($selected)!==4)ng_fail('Asset scope');
  if(in_array($mode,['--verify','--rollback-preview','--rollback'])){if(!$backup)ng_fail('Missing backup');ng_stable($backup['before'],$now);if($now['content']!==$backup['after']||$now['seo_title']!==$t['seo_title']||$now['meta_description']!==$t['meta_description'])ng_fail('Published drift');}
  else{if($backup!==null)ng_fail('Already applied');if(hash('sha256',$now['content'])!==$t['before_content_sha256']||$now['h1']!==$t['h1_preserved']||$now['gallery']!==$t['gallery_preserved']||$now['url']!==$t['url'])ng_fail('Baseline drift');if($now['seo_title']!==$t['before_seo_title']||$now['meta_description']!==$t['before_meta_description']||hash('sha256',$now['excerpt'])!==$t['before_excerpt_sha256'])ng_fail('Baseline SEO/excerpt drift');foreach($t['baseline_protected'] as $k=>$h)if(hash('sha256',serialize(get_post_meta($id,$k,true)))!==$h)ng_fail('Baseline protected drift');}
  if($mode==='--apply'){
   $journal='_shustrik_five_country_stl_slider_media_20261006_'.$id;if(get_option($journal,null)!==null)ng_fail('Media journal exists; inspect before retry');if(!add_option($journal,['status'=>'importing','ids'=>[]],'',false))ng_fail('Journal');
   require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$ids=[];
   foreach($selected as $m){$tmp=wp_tempnam($m['file']);if(!copy(__DIR__.'/'.$m['file'],$tmp))ng_fail('Copy');$aid=media_handle_sideload(['name'=>$m['file'],'tmp_name'=>$tmp],$id,$m['caption']);if(is_wp_error($aid))ng_fail('Import');$ids[]=$aid;update_option($journal,['status'=>'importing','ids'=>$ids],false);$r=wp_update_post(wp_slash(['ID'=>$aid,'post_title'=>$m['title'],'post_excerpt'=>$m['caption'],'post_content'=>$m['caption']]),true);if(is_wp_error($r))ng_fail('Media metadata');update_post_meta($aid,'_wp_attachment_image_alt',wp_slash($m['alt']));}
   $after=str_replace('{{IMAGE_IDS}}',implode(',',$ids),$t['description']);if(strpos($after,'{{')!==false)ng_fail('Placeholder');$backup=['utc'=>gmdate('c'),'before'=>$now,'after'=>$after,'media_ids'=>$ids];if(!add_option($key,$backup,'',false))ng_fail('Backup exists');
   global $wpdb;$wpdb->query('START TRANSACTION');try{$wpdb->get_var($wpdb->prepare("SELECT ID FROM {$wpdb->posts} WHERE ID=%d FOR UPDATE",$id));clean_post_cache($id);if(ng_state($id)!==$now)ng_fail('Concurrent edit');$n=$wpdb->query($wpdb->prepare("UPDATE {$wpdb->posts} SET post_content=%s,post_modified=%s,post_modified_gmt=%s WHERE ID=%d AND post_content=%s",$after,current_time('mysql'),current_time('mysql',true),$id,$now['content']));if($n!==1)ng_fail('Write');update_post_meta($id,'_yoast_wpseo_title',wp_slash($t['seo_title']));update_post_meta($id,'_yoast_wpseo_metadesc',wp_slash($t['meta_description']));clean_post_cache($id);$written=ng_state($id);ng_stable($now,$written);if($written['content']!==$after||$written['seo_title']!==$t['seo_title']||$written['meta_description']!==$t['meta_description'])ng_fail('Written state');$wpdb->query('COMMIT');}catch(Throwable $e){$wpdb->query('ROLLBACK');clean_post_cache($id);throw $e;}
   ng_refresh($id);ng_stable($now,ng_state($id));update_option($journal,['status'=>'published','ids'=>$ids],false);
  }
  if($mode==='--rollback'){$b=$backup['before'];$r=wp_update_post(wp_slash(['ID'=>$id,'post_content'=>$b['content']]),true);if(is_wp_error($r))ng_fail('Rollback');update_post_meta($id,'_yoast_wpseo_title',wp_slash($b['seo_title']));update_post_meta($id,'_yoast_wpseo_metadesc',wp_slash($b['meta_description']));ng_refresh($id);ng_stable($b,ng_state($id));}
  $images=[];if($mode==='--verify'){foreach($backup['media_ids'] as $i=>$aid){$m=$selected[$i];$p=get_post($aid);$d=wp_get_attachment_metadata($aid);if(!$p||$p->post_title!==$m['title']||$p->post_excerpt!==$m['caption']||get_post_meta($aid,'_wp_attachment_image_alt',true)!==$m['alt']||get_post_mime_type($aid)!=='image/jpeg'||$d['width']!==1500||$d['height']!==1000||hash_file('sha256',get_attached_file($aid))!==$m['sha256'])ng_fail('Media drift');$images[]=['id'=>$aid,'url'=>wp_get_attachment_url($aid),'title'=>$m['title'],'alt'=>$m['alt']];}}
  $out[]=['id'=>$id,'url'=>$now['url'],'seo_title'=>$t['seo_title'],'meta_description'=>$t['meta_description'],'h1'=>$now['h1'],'media'=>$images,'protected_preserved'=>true];
 }
 echo json_encode(['ok'=>true,'mode'=>$mode,'utc'=>gmdate('c'),'rows'=>$out],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";
}catch(Throwable $e){echo json_encode(['ok'=>false,'reason'=>$e instanceof RuntimeException?$e->getMessage():'Internal error'])."\n";exit(1);}
