<?php
ini_set('display_errors','0');define('WP_USE_THEMES',false);ob_start();require '/var/www/html/wp-load.php';ob_end_clean();
function fail_slider($s){throw new RuntimeException($s);}
function capture_slider($id){$p=get_post($id);if(!$p||$p->post_type!=='product')fail_slider('Product missing');$protected=[];foreach(['_price','_regular_price','_sale_price','_sku','_stock','_stock_status','_downloadable','_virtual','_downloadable_files','_thumbnail_id','_product_image_gallery','_yoast_wpseo_canonical','_yoast_wpseo_meta-robots-noindex','_yoast_wpseo_meta-robots-nofollow'] as $k)$protected[$k]=hash('sha256',serialize(get_post_meta($id,$k,true)));return ['id'=>$id,'url'=>get_permalink($id),'h1'=>$p->post_title,'excerpt'=>$p->post_excerpt,'content'=>$p->post_content,'seo_title'=>get_post_meta($id,'_yoast_wpseo_title',true),'meta_description'=>get_post_meta($id,'_yoast_wpseo_metadesc',true),'gallery'=>get_post_meta($id,'_product_image_gallery',true),'protected'=>$protected,'shared_block_hash'=>hash('sha256',get_post(9586)->post_content)];}
function stable_slider($a,$b){foreach(['url','h1','excerpt','gallery','protected','shared_block_hash'] as $k)if($a[$k]!==$b[$k])fail_slider('Protected drift '.$a['id'].' '.$k);}
function refresh_slider($id){clean_post_cache($id);wp_cache_delete($id,'post_meta');if(function_exists('YoastSEO')&&class_exists('Yoast\\WP\\SEO\\Builders\\Indexable_Builder'))YoastSEO()->classes->get('Yoast\\WP\\SEO\\Builders\\Indexable_Builder')->build_for_id_and_type($id,'post');}
try{
 if(PHP_SAPI!=='cli'||rtrim(home_url(),'/')!=='https://shustrik-maps.com')fail_slider('Site');$mode=$argv[1]??'--preview';if(!in_array($mode,['--preview','--apply-california','--apply-arizona','--verify','--rollback-preview','--rollback']))fail_slider('Mode');
 $targets=json_decode(file_get_contents(__DIR__.'/manifest.json'),true,512,JSON_THROW_ON_ERROR)['rows'];$media=json_decode(file_get_contents(__DIR__.'/media.json'),true,512,JSON_THROW_ON_ERROR);if(array_column($targets,'id')!==[9522,9520]||count($media)!==4)fail_slider('Scope');foreach($media as $m)if(hash_file('sha256',__DIR__.'/'.$m['file'])!==$m['sha256'])fail_slider('Asset hash');
 $scope=$mode==='--apply-california'?[9522]:($mode==='--apply-arizona'?[9520]:[9522,9520]);$out=[];
 foreach($targets as $t){$id=$t['id'];if(!in_array($id,$scope))continue;$key='_shustrik_stl_slider_backup_20261006_'.$id;$backup=get_option($key,null);$now=capture_slider($id);
  if(in_array($mode,['--verify','--rollback-preview','--rollback'])){if(!$backup)fail_slider('Backup missing '.$id);stable_slider($backup['before'],$now);if($now['content']!==$backup['after_content']||$now['seo_title']!==$t['seo_title']||$now['meta_description']!==$t['meta_description'])fail_slider('Published drift '.$id);}
  else{if($backup!==null)fail_slider('Already applied '.$id);if(hash('sha256',$now['content'])!==$t['before_content_sha256']||$now['h1']!==$t['h1_preserved']||$now['gallery']!==$t['gallery_preserved'])fail_slider('Baseline drift '.$id);}
  if(strpos($mode,'--apply-')===0){
   $content=$t['description'];$newids=[];
   if($id===9520){if(!get_option('_shustrik_stl_slider_backup_20261006_9522'))fail_slider('California must be published first');$journal='_shustrik_arizona_slider_media_20261006';if(get_option($journal,null)!==null)fail_slider('Media journal exists; inspect before retry');if(!add_option($journal,['status'=>'importing','ids'=>[]],'',false))fail_slider('Journal');require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';
    foreach($media as $m){$tmp=wp_tempnam($m['file']);if(!copy(__DIR__.'/'.$m['file'],$tmp))fail_slider('Asset copy');$aid=media_handle_sideload(['name'=>$m['file'],'tmp_name'=>$tmp],$id,$m['caption']);if(is_wp_error($aid))fail_slider('Media import');$newids[]=$aid;update_option($journal,['status'=>'importing','ids'=>$newids],false);$r=wp_update_post(wp_slash(['ID'=>$aid,'post_title'=>$m['title'],'post_excerpt'=>$m['caption'],'post_content'=>$m['caption']]),true);if(is_wp_error($r))fail_slider('Media metadata');update_post_meta($aid,'_wp_attachment_image_alt',wp_slash($m['alt']));}
    $content=str_replace('{{ARIZONA_SLIDER_IMAGE_IDS}}',implode(',',$newids),$content);
   }
   if(strpos($content,'{{')!==false)fail_slider('Unresolved placeholder');if(!add_option($key,['utc'=>gmdate('c'),'before'=>$now,'after_content'=>$content,'media_ids'=>$newids],'',false))fail_slider('Backup exists');
   global $wpdb;$wpdb->query('START TRANSACTION');try{$wpdb->get_var($wpdb->prepare("SELECT ID FROM {$wpdb->posts} WHERE ID=%d FOR UPDATE",$id));clean_post_cache($id);if(capture_slider($id)!==$now)fail_slider('Concurrent edit '.$id);$n=$wpdb->query($wpdb->prepare("UPDATE {$wpdb->posts} SET post_content=%s,post_modified=%s,post_modified_gmt=%s WHERE ID=%d AND post_content=%s",$content,current_time('mysql'),current_time('mysql',true),$id,$now['content']));if($n!==1)fail_slider('Write '.$id);update_post_meta($id,'_yoast_wpseo_title',wp_slash($t['seo_title']));update_post_meta($id,'_yoast_wpseo_metadesc',wp_slash($t['meta_description']));refresh_slider($id);$written=capture_slider($id);stable_slider($now,$written);if($written['content']!==$content||$written['seo_title']!==$t['seo_title']||$written['meta_description']!==$t['meta_description'])fail_slider('Written state');$wpdb->query('COMMIT');}catch(Throwable $e){$wpdb->query('ROLLBACK');clean_post_cache($id);throw $e;}
   if($id===9520)update_option($journal,['status'=>'published','ids'=>$newids],false);if(function_exists('rocket_clean_files'))rocket_clean_files([$now['url']]);do_action('litespeed_purge_url',$now['url']);$backup=get_option($key);
  }
  if($mode==='--rollback'){$b=$backup['before'];$r=wp_update_post(wp_slash(['ID'=>$id,'post_content'=>$b['content']]),true);if(is_wp_error($r))fail_slider('Rollback write');update_post_meta($id,'_yoast_wpseo_title',wp_slash($b['seo_title']));update_post_meta($id,'_yoast_wpseo_metadesc',wp_slash($b['meta_description']));refresh_slider($id);if(function_exists('rocket_clean_files'))rocket_clean_files([$b['url']]);do_action('litespeed_purge_url',$b['url']);}
  $images=[];if($mode==='--verify'&&$id===9520){foreach($backup['media_ids'] as $i=>$aid){$m=$media[$i];$p=get_post($aid);$d=wp_get_attachment_metadata($aid);if(!$p||$p->post_title!==$m['title']||$p->post_excerpt!==$m['caption']||get_post_meta($aid,'_wp_attachment_image_alt',true)!==$m['alt']||get_post_mime_type($aid)!=='image/jpeg'||$d['width']!==1500||$d['height']!==1000||hash_file('sha256',get_attached_file($aid))!==$m['sha256'])fail_slider('Media drift');$images[]=['id'=>$aid,'url'=>wp_get_attachment_url($aid),'title'=>$m['title'],'alt'=>$m['alt']];}}
  $out[]=['id'=>$id,'url'=>$now['url'],'seo_title'=>$t['seo_title'],'meta_description'=>$t['meta_description'],'media'=>$images,'media_ids'=>$backup['media_ids']??[],'protected_preserved'=>true];
 }
 echo json_encode(['ok'=>true,'mode'=>$mode,'utc'=>gmdate('c'),'rows'=>$out],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";
}catch(Throwable $e){echo json_encode(['ok'=>false,'reason'=>$e instanceof RuntimeException?$e->getMessage():'Internal error'])."\n";exit(1);}
