from pathlib import Path
import json,re,shutil,datetime
root=Path(__file__).parent;project=root.parent;repo=Path('J:/1. My Vault/90 Migration/shustrik-maps-seo');out=repo/'final-two-stl-slider-release-20261008'
def read(n):
 s=(root/n).read_text(encoding='utf-8-sig')
 try:return json.loads(s)
 except json.JSONDecodeError:return json.loads(next(x for x in s.splitlines() if x.startswith('{')))
def write(n,data): (root/n).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
manifest=read('manifest.json');verify=read('verify.json');deploy=read('deployment.json');public=read('public-qa.json');pres=read('preservation-qa.json');roll=read('rollback-preview.json')
assert verify['ok'] and public['pass'] and pres['pass'] and roll['ok']
assert len(verify['rows'])==2 and sum(len(r['media']) for r in verify['rows'])==8 and len(public['rows'])==4 and len(public['media'])==8
catalog=json.loads(Path('J:/1. My Vault/.codex-work/final-catalog.json').read_text(encoding='utf-8-sig'))
icon=r'<img\b[^>]*src="[^"]*\bSTL[^"]*"'
candidates=[x for x in catalog if 'AI-generated' not in x['content'] and re.search(icon,x['excerpt'],re.I)]
assert {x['id'] for x in candidates}=={9512,9516},[(x['id'],x['title']) for x in candidates]
audit={'total_published_products':len(catalog),'listed_stl_icon_products':sum(bool(re.search(icon,x['excerpt'],re.I)) for x in catalog),'eligible_unprocessed':[],'eligible_unprocessed_count':0,'exclusions':[{'id':x['id'],'title':x['title'],'reason':'Owner excludes Belarus' if x['id']==9512 else 'Previously processed per project release logs; legacy layout retained'} for x in candidates],'criterion':'Fresh published catalog, own AI concepts absent and explicit STL format icon; exclude owner scope Belarus and historical completed Denmark. C4D-only/on-request conversions are not substitutions.'}
write('remaining-stl-audit.json',audit)
for mode in ['desktop','mobile']:
 qa=read('moon-surface-'+mode+'-qa.json');assert len(qa)==4 and all(x['visible_count']==1 and x['arrows']==2 and x['dots']==4 and not x['overflow'] and x['active'][0]['loaded'] for x in qa)
 assert read('moon-surface-'+mode+'-controls.json')['pass']
write('browser-scope.json',{'owner_instruction':'Проверять переключение слайдов на компьютере и телефоне не нужно. Я это сделаю сам.','moon_surface_completed_before_instruction':{'slides_desktop':4,'slides_mobile':4,'arrows_and_dots_pass':True},'female_face_switching':'Not performed per latest owner instruction; owner will check. First slide publication screenshot saved.','additional_switching_tests':False})
stamp=datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
table='| Товар | ID | Опубликованные media |\n| --- | --- | --- |\n'
for r in verify['rows']:table+='| ['+next(m['name'] for m in manifest['rows'] if m['id']==r['id'])+']('+r['url']+') | '+str(r['id'])+' | '+', '.join(str(m['id']) for m in r['media'])+' |\n'
report='# Финальные два STL — Release Report\n\nДата: '+stamp+' МСК. External WordPress, https://shustrik-maps.com.\n\nПо запросу следующих пяти свежая сверка оставила только два допустимых необработанных товара. Оба опубликованы и проверены в согласованном объёме; дальнейшую проверку переключения слайдов владелец взял на себя.\n\n'+table
report+='\n## Отбор и семантика\n\nКаталог '+str(len(catalog))+' опубликованных товаров, '+str(audit['listed_stl_icon_products'])+' с явным STL format icon. После этой партии допустимых необработанных STL **0**. Belarus9512 исключён владельцем; Denmark9516 ранее обработан, см. [[../Ten More Global STL Sliders 2026-10-07/Release Report]]. C4D-only товары с конверсией по запросу не подставлялись. [[remaining-stl-audit.json]].\n\nGoogle, English, USA параметры hl=en/gl=us/pws=0; фактическая локация выдачи Unknown. Moon surface/lunar terrain STL: цифровые платные модели, рядом free generators/NASA/globes/game terrain. Abstract female face relief STL: цифровые decorative relief/CNC модели, рядом bust/free sculpture. Измеренные частотности, позиции и difficulty не получены. [[semantic-review.json]], [[intent-evidence.json]], [[google-moon-surface.txt]], [[google-female-face.txt]], [[Page Briefs]].\n'
report+='\n## Изменения и сохранность\n\nИзменены только SEO title/meta и первый illustration-блок Description. У Moon заменён один woodmart_image16744. У Female Face заменена только illustration-only section16813; исходный introductory paragraph сохранён дословно и расположен рядом со слайдером. Все остальные исходные тексты, excerpts, H1, URLs, specs, цены, файлы/downloads, верхние галереи, sample renders, Internet ideas galleries, internal links, payment/shared HTML blocks сохранены. Сравнение всех protected postmeta хэшей также прошло. '+str(sum(x['old_media_preserved'] for x in pres['rows']))+' прежних media из baseline сохранены, старые иллюстрации не удалены. [[baseline.json]], [[after.json]], [[preservation-qa.json]].\n\nСозданы8 native ImageGen концептов по собственным4 product references. Каждый результат осмотрен: desktop ivory plastic/solid full backing; small wall relief; gift box; large grey concrete panel. Moon — квадратный lunar tile; Female — высокая прямоугольная geometric face panel, без bust. У Female исходная Base: Open сохранена, сплошная подложка концепта — дополнительная fabrication. PNG originals/prompts/references сохранены. Настоящие RGB JPEG1500×1000; AI title/alt/caption, SHA256. [[jobs.json]], [[native-registry.json]], [[visual-review.json]], [[uploaded-media.json]].\n\nСлайдер: один слайд desktop/mobile, четыре изображения, ручные стрелки и точки, без autoplay/wrap. Под ним только жирная центрованная AI-generated application concepts.\n'
report+='\n## Проверки\n\n- Guarded DB/SEO/content/protected data:2/2; media metadata/MIME/dimensions/hash:8/8.\n- Public HTTP/cache-bypass SEO title/meta/H1/canonical/indexability/Product schema/cart/raw-shortcodes/short notice:4/4; media HEAD200/image/jpeg:8/8. [[public-qa.json]], [[verify.json]].\n- Backup matches original baseline2/2; guarded rollback-preview2/2. [[backup-export.json]], [[rollback-preview.json]].\n- До уточнения владельца Moon Surface:4slides×desktop/mobile=8, Next/Previous/dots passed. Female Face переключение не проверялось по прямому указанию владельца: «Проверять переключение слайдов на компьютере и телефоне не нужно. Я это сделаю сам». Скриншот первого опубликованного слайда сохранён. [[browser-scope.json]].\n- WireGuard SSH/sudoDocker available; WP/DB running, restart0, StartedAt иports before/after совпали. WP127.0.0.1:8083; DB безpublished ports. Build/restart/local runtime changes нет. [[server-runtime-before.txt]], [[runtime-before.txt]], [[runtime-after.txt]].\n'
report+='\n## GitHub, точный source и откат\n\nGitHub-first fetch/prune/main/origin, source baseline2dfe29da75253c69a1aa026a1ec1fea37d883c90, upstream0:0. Прежние unrelated dirty/untracked сохранены; staged только новая release-folder. Published source **'+deploy['commit']+'** pushed. Exact git archive SHA256 **'+deploy['archive_sha256']+'**, local/VPS hashes совпали, PHP lint прошёл. [[github-first.json]], [[deployment.json]]. Apply выполнен один раз; предыдущие release.php не запускались.\n\nDurable WordPress options _shustrik_final_two_stl_slider_backup_20261008_16743 и _shustrik_final_two_stl_slider_backup_20261008_16812, соответствующие media journals. Полный экспорт before/after сохранён отдельно. Проверка и откат только при отсутствии последующих изменений:\n\n    ssh vpsadmin@10.66.66.1 "sudo -n docker exec shustrik-maps-wordpress-1 php '+deploy['wp_source']+'/release.php --rollback-preview"\n    ssh vpsadmin@10.66.66.1 "sudo -n docker exec shustrik-maps-wordpress-1 php '+deploy['wp_source']+'/release.php --rollback"\n\nRollback восстанавливает прежние Description/SEO, media не удаляет. Повторный apply не идемпотентен, запрещён без разбора фактического состояния.\n'
report+='\n## Следующие действия\n\nНовых допустимых необработанных STL нет. Владелец проверит переключения слайдов. P1 analytics/recovery/consent, index check10.10, yellow/degraded сохранены; mesh/readiness/accuracy/production rights не проверялись и новыми обещаниями не заменялись.\n\n![Опубликованная Female Face](published-female-face-proof.png)\n'
(root/'Release Report.md').write_text(report,encoding='utf-8',newline='\n')
note='## Финальные два STL — '+stamp+' МСК\n\nMoon Surface16743 и Abstract Female Face Silhouette16812: SEO и8JPEG опубликованы; DB2/2, media8/8, HTTP4/4, rollback-preview2/2 passed. Исходные тексты/H1/URL/commerce/files/верхние галереи/shared blocks и старые media сохранены. Source '+deploy['commit']+' pushed и доставлен точным архивом; apply один раз. Fresh516 product audit: допустимых необработанных STL0; Belarus исключён, Denmark ранее завершён. Переключения слайдов владелец проверяет сам; Moon8checks завершены до уточнения, Female переключения не проверялись. SSH/sudoDocker available, WP/DB runtime unchanged, без build/restart. P1 analytics/recovery/consent,index10.10,yellow/degraded сохранены. [[Final Two STL Sliders 2026-10-08/Release Report]].\n\n'
for filename in ['Shustrik Maps SEO - Overview.md','Shustrik Maps SEO - Next Actions.md']:
 p=project/filename;s=p.read_text(encoding='utf-8-sig');fm=re.match(r'---\n.*?\n---\n',s,re.S);assert fm
 if 'Overview' in filename:
  head=re.sub(r'^current_commit:.*$', 'current_commit: '+deploy['commit'],fm.group(),flags=re.M)
  head=re.sub(r'^last_runtime_check:.*$', 'last_runtime_check: '+stamp,head,flags=re.M)
  s=head+s[fm.end():];assert 'health: yellow' in head and 'runtime_status: degraded' in head and 'priority: high' in head
 pos=s.index('\n---\n')+5;s=s[:pos]+'\n'+note+s[pos:].lstrip('\n');p.write_text(s,encoding='utf-8',newline='\n')
p=Path('J:/1. My Vault/04 Operations/Runtime Status.md');s=p.read_text(encoding='utf-8-sig')
runtime='## Targeted Shustrik Maps — Final Two STL, '+stamp+' МСК\n\nExternal https://shustrik-maps.com; source '+deploy['commit']+', archive '+deploy['archive_sha256']+' local/VPS matched. DB2/2,media8/8,HTTP4/4,rollback-preview2/2 passed. Переключения слайдов владелец проверит сам; Moon8 checks до уточнения completed, Female switching not performed. SSH WireGuard/sudoDocker available; WP/DB running/restart0/StartedAt/ports unchanged, WP127.0.0.1:8083/DB no published ports. No build/restart/local runtime change. Eligible unprocessed listed STL0 after excluding Belarus and historically completed Denmark. P1 analytics/recovery/consent,index10.10,yellow/degraded сохранены; другие проекты этим адресным срезом не проверялись. [[01 Projects/WordPress/shustrik-maps.com/Final Two STL Sliders 2026-10-08/Release Report]].\n\n'
p.write_text(runtime+s,encoding='utf-8',newline='\n')
for p in root.iterdir():
 if p.is_file() and p.suffix in ['.py','.php','.json','.md','.png','.jpg','.txt']:
  dest=out/p.name
  if p.suffix in ['.py','.php','.json','.md','.txt']:dest.write_text('\n'.join(x.rstrip() for x in p.read_text(encoding='utf-8-sig').splitlines()).rstrip()+'\n',encoding='utf-8',newline='\n')
  else:shutil.copy2(p,dest)
print(json.dumps({'eligible_remaining':0,'published_products':2,'new_media':8,'owner_checks_switching':True,'report':str(root/'Release Report.md')},ensure_ascii=False))
