from pathlib import Path
import json,shutil
root=Path('J:/1. My Vault/01 Projects/WordPress/shustrik-maps.com/Five Mixed STL Sliders 2026-10-08');out=Path('J:/1. My Vault/90 Migration/shustrik-maps-seo/five-mixed-stl-slider-release-20261008')
obs={'initial_observation':'Zimbabwe desktop screenshot was blank although DOM active/visible/loaded checks passed. Mobile image was visible.','recheck':'Viewport refresh rendered the image; subsequent fresh desktop reload without resize showed the first image. Repeated four-slide desktop controls passed, first and second scenes visually seen. No WordPress content or container changes used for this recheck.','root_cause':'Not established; recorded as transient browser rendering observation, not proof of a specific CSS defect.','final_desktop_screenshot':'zimbabwe-desktop.png','pass':True}
(root/'zimbabwe-render-recheck.json').write_text(json.dumps(obs,ensure_ascii=False,indent=2),encoding='utf-8');shutil.copy2(root/'zimbabwe-render-recheck.json',out/'zimbabwe-render-recheck.json')
p=root/'Release Report.md';s=p.read_text(encoding='utf-8');s=s.replace('WireGuard SSH vpsadmin@10.66.66.1','Zimbabwe: первоначальный desktop-кадр был пустым при успешных DOM checks. После viewport refresh и затем свежей загрузки без resize изображение видно; повторные четыре desktop-слайда/controls passed, первые две сцены осмотрены визуально. Причина первоначального кадра не установлена; WordPress не менялся и apply не повторялся. Итоговый desktop screenshot обновлён. [[zimbabwe-render-recheck.json]].\n\nWireGuard SSH vpsadmin@10.66.66.1');p.write_text(s,encoding='utf-8');shutil.copy2(p,out/p.name)
p=root/'Page Briefs.md';s=p.read_text(encoding='utf-8').replace('Primary: Artistic Geoid topographic map STL. Support: terrain STL / relief map STL / 3D print / CNC terrain.','Primary: artistic geoid height STL. Support: artistic Earth gravity surface STL / decorative geoid 3D print.').replace('Primary: Modular Earth Globe topographic map STL. Support: terrain STL / relief map STL / 3D print / CNC terrain.','Primary: modular Earth globe STL. Support:12-part regular dodecahedron globe STL / puzzle globe3Dprint / assembly.').replace('Primary: Israel Extended Coverage topographic map STL.','Primary: Israel terrain STL, extended coverage as an editorial SKU differentiator.');p.write_text(s,encoding='utf-8');shutil.copy2(p,out/p.name)
for p in out.glob('google-*.txt'):
 s=p.read_text(encoding='utf-8');p.write_text('\n'.join(x.rstrip() for x in s.splitlines())+'\n',encoding='utf-8')
shutil.copy2(root/'git-receipt-next.py',out/'git-receipt-next.py');shutil.copy2(root/'finish-evidence-next.py',out/'finish-evidence-next.py');shutil.copy2(Path(__file__),out/'finish-mixed-evidence.py')
print('Final render observation, distinct page briefs and evidence saved')
