<?php
ini_set('display_errors','0');define('WP_USE_THEMES',false);ob_start();require '/var/www/html/wp-load.php';ob_end_clean();
function fail_arizona($s){throw new RuntimeException($s);}
function protected_arizona($b){foreach($b['protected'] as $k=>$v){if($k==='_product_image_gallery')continue;if(hash('sha256',serialize(get_post_meta(9520,$k,true)))!==$v)fail_arizona('Protected field drift: '.$k);} $p=get_post(9520);if($p->post_title!==$b['title']||$p->post_excerpt!==$b['excerpt']||get_permalink(9520)!==$b['url'])fail_arizona('Identity/excerpt drift');}
function refresh_arizona(){clean_post_cache(9520);wp_cache_delete(9520,'post_meta');if(function_exists('YoastSEO')&&class_exists('Yoast\\WP\\SEO\\Builders\\Indexable_Builder'))YoastSEO()->classes->get('Yoast\\WP\\SEO\\Builders\\Indexable_Builder')->build_for_id_and_type(9520,'post');}
try{
 if(PHP_SAPI!=='cli'||rtrim(home_url(),'/')!=='https://shustrik-maps.com')fail_arizona('Site');
 $mode=$argv[1]??'--preview';if(!in_array($mode,['--preview','--apply','--verify','--rollback-preview','--rollback']))fail_arizona('Mode');
 $b=json_decode(file_get_contents(__DIR__.'/baseline.json'),true,512,JSON_THROW_ON_ERROR);$m=json_decode(file_get_contents(__DIR__.'/manifest.json'),true,512,JSON_THROW_ON_ERROR);$key='_shustrik_arizona_visual_backup_20261005';$backup=get_option($key,null);
 if($b['id']!==9520||$m['product_id']!==9520||count($m['media'])!==3)fail_arizona('Scope');protected_arizona($b);
 foreach($m['media'] as $a)if(hash_file('sha256',__DIR__.'/'.$a['file'])!==$a['sha256'])fail_arizona('Asset hash');
 $after=in_array($mode,['--verify','--rollback-preview','--rollback']);$p=get_post(9520);
 if($after){if(!$backup||$p->post_content!==$backup['content_after']||get_post_meta(9520,'_product_image_gallery',true)!==$backup['gallery_after']||get_post_meta(9520,'_yoast_wpseo_metadesc',true)!==$m['meta_description'])fail_arizona('Published state drift');}
 else {if($backup!==null||hash('sha256',$p->post_content)!==$m['before_content_sha256']||$p->post_content!==$b['content']||get_post_meta(9520,'_product_image_gallery',true)!==$b['gallery']||get_post_meta(9520,'_yoast_wpseo_title',true)!==$b['seo_title']||get_post_meta(9520,'_yoast_wpseo_metadesc',true)!==$b['meta_description'])fail_arizona('Baseline drift');}
 if(in_array($mode,['--preview','--rollback-preview'])){echo json_encode(['ok'=>true,'mode'=>$mode,'product'=>9520,'media'=>3,'protected_preserved'=>true])."\n";exit;}
 if($mode==='--verify'){
  $media=[];foreach($backup['ids'] as $i=>$id){$a=$m['media'][$i];if(get_post($id)->post_title!==$a['title']||get_post_meta($id,'_wp_attachment_image_alt',true)!==$a['alt']||get_post($id)->post_excerpt!==$a['caption'])fail_arizona('Media metadata');$media[]=['id'=>$id,'url'=>wp_get_attachment_url($id),'title'=>$a['title'],'alt'=>$a['alt']];}
  echo json_encode(['ok'=>true,'mode'=>$mode,'utc'=>gmdate('c'),'media'=>$media,'protected_preserved'=>true,'backup_option'=>$key],JSON_UNESCAPED_SLASHES)."\n";exit;
 }
 if($mode==='--rollback'){$res=wp_update_post(wp_slash(['ID'=>9520,'post_content'=>$b['content']]),true);if(is_wp_error($res))fail_arizona('Rollback content');update_post_meta(9520,'_product_image_gallery',$b['gallery']);update_post_meta(9520,'_yoast_wpseo_metadesc',wp_slash($b['meta_description']));refresh_arizona();echo json_encode(['ok'=>true,'mode'=>$mode,'media_retained'=>true])."\n";exit;}
 require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';
 $ids=[];$figures='';
 foreach($m['media'] as $a){$tmp=wp_tempnam($a['file']);if(!copy(__DIR__.'/'.$a['file'],$tmp))fail_arizona('Copy');$id=media_handle_sideload(['name'=>$a['file'],'tmp_name'=>$tmp],9520,$a['caption']);if(is_wp_error($id))fail_arizona('Media import');$ids[]=$id;wp_update_post(wp_slash(['ID'=>$id,'post_title'=>$a['title'],'post_excerpt'=>$a['caption'],'post_content'=>$a['caption']]));update_post_meta($id,'_wp_attachment_image_alt',wp_slash($a['alt']));$figures.='<figure style="margin:24px 0">'.'<h3>'.esc_html($a['heading']).'</h3>'.wp_get_attachment_image($id,'large',false,['alt'=>$a['alt'],'title'=>$a['title'],'loading'=>'lazy','style'=>'width:100%;height:auto;border-radius:4px']).'<figcaption style="font-size:14px;line-height:1.5;margin-top:8px">'.esc_html($a['caption']).'</figcaption></figure>';}
 $content=str_replace('{{AI_FIGURES}}',$figures,$m['content_template']);$gallery=$b['gallery'].','.implode(',',$ids);
 if(!add_option($key,['utc'=>gmdate('c'),'baseline'=>$b,'ids'=>$ids,'content_after'=>$content,'gallery_after'=>$gallery],'',false))fail_arizona('Backup');
 global $wpdb;$wpdb->query('START TRANSACTION');try{$wpdb->get_var($wpdb->prepare("SELECT ID FROM {$wpdb->posts} WHERE ID=%d FOR UPDATE",9520));clean_post_cache(9520);if(get_post(9520)->post_content!==$b['content'])fail_arizona('Concurrent content drift');protected_arizona($b);$ok=$wpdb->query($wpdb->prepare("UPDATE {$wpdb->posts} SET post_content=%s,post_modified=%s,post_modified_gmt=%s WHERE ID=%d AND post_content=%s",$content,current_time('mysql'),current_time('mysql',true),9520,$b['content']));if($ok!==1)fail_arizona('Guarded update');update_post_meta(9520,'_product_image_gallery',$gallery);update_post_meta(9520,'_yoast_wpseo_metadesc',wp_slash($m['meta_description']));refresh_arizona();protected_arizona($b);if(get_post(9520)->post_content!==$content)fail_arizona('Content verification');$wpdb->query('COMMIT');}catch(Throwable $e){$wpdb->query('ROLLBACK');throw $e;}
 if(function_exists('rocket_clean_files'))rocket_clean_files([$b['url']]);do_action('litespeed_purge_url',$b['url']);echo json_encode(['ok'=>true,'mode'=>$mode,'utc'=>gmdate('c'),'product'=>9520,'media_ids'=>$ids,'backup_option'=>$key])."\n";
}catch(Throwable $e){echo json_encode(['ok'=>false,'reason'=>$e instanceof RuntimeException?$e->getMessage():'Internal error'])."\n";exit(1);}
