from pathlib import Path
import json,shutil,re,subprocess
from datetime import datetime,timezone,timedelta
root=Path(__file__).parent;proj=root.parent;lunar=proj/'Next Lunar Sliders 2026-10-08';repo=Path('J:/1. My Vault/90 Migration/shustrik-maps-seo');vault=Path('J:/1. My Vault')
def read(p):
 s=p.read_text(encoding='utf-8-sig')
 try:return json.loads(s)
 except json.JSONDecodeError:return json.loads(next(x for x in s.splitlines() if x.startswith('{')))
stamp=datetime.now(timezone(timedelta(hours=3))).strftime('%Y-%m-%d %H:%M');combined=[];protected=[];page=[];media=[];checks=[];controls=[];deploy=[]
for part in [root,lunar]:
 v=read(part/'verify.json');p=read(part/'preservation-qa.json');h=read(part/'public-qa.json');assert v['ok'] and p['pass'] and h['pass'];combined+=v['rows'];protected+=p['rows'];page+=h['rows'];media+=h['media'];deploy.append(read(part/'deployment.json'))
 assert read(part/'rollback-preview.json')['ok'] and p['runtime_unchanged']
 for id,slug,name in read(part/'defs.json'):
  for mode in ['desktop','mobile']:
   a=read(part/(slug+'-'+mode+'-qa.json'));assert len(a)==4;checks+=a;c=read(part/(slug+'-'+mode+'-controls.json'));assert c['pass'];controls.append({'id':id,'mode':mode,'pass':True})
assert len(combined)==5 and len(media)==20 and len(page)==10 and len(checks)==40 and len(controls)==10
qa={'pass':True,'products':combined,'protected':protected,'public_pages':10,'media':20,'slide_checks':40,'control_sets':controls,'sources':deploy}
(root/'final-five-qa.json').write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(lunar/'browser-qa.json').write_text(json.dumps({'pass':True,'slide_checks':16,'samples':checks[-16:],'control_sets':controls[-4:]},indent=2)+'\n',encoding='utf-8')
catalog=read(root/'catalog-audit.json');remaining=[r for r in catalog['remaining_by_stl_icon'] if r['id'] not in [9512,9516]];assert [r['id'] for r in remaining]==[16743,16812]
catalog['scope_pending']='Resolved: Copernicus and Theophilus are actual listed STL+C4D products; included to complete five. Architecture conversion-on-request products are excluded.'
catalog['confirmed_remaining_stl']=remaining
(root/'catalog-audit.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
correction='# Scope correction\n\nInitial title/excerpt keyword screening missed four STL-icon products. The first three own-reference cards were already published once. The subsequent format-icon audit found Copernicus Lunar Crater16696, Theophilus Lunar Crater16728, Moon Surface16743 and Abstract Female Face Silhouette16812. Copernicus and Theophilus are explicitly STL+C4D in their specifications and were selected to complete the owner-requested five. The earlier suggestion to use Burj architecture conversions and the claim of only three remaining are superseded. No C4D-only conversion product was published. Denmark is excluded by the historical completion record; Belarus excluded by owner.\n'
(root/'Scope Correction.md').write_text(correction,encoding='utf-8')
old=sum(x['old_media_preserved'] for x in protected)
table='| Товар | ID | Новые media |\n|---|---:|---|\n'+''.join('| ['+r['h1']+']('+r['url']+') | '+str(r['id'])+' | '+', '.join(str(m['id']) for m in r['media'])+' |\n' for r in combined)
report='---\ntype: release-report\nproject_id: shustrik-maps-seo\nstatus: published-and-verified\ncreated_at: '+stamp+'\ndeployment_mode: external\ndeployment_target: https://shustrik-maps.com\nsource_commits: ['+', '.join(d['commit'] for d in deploy)+']\nnext_action: Обработать оставшиеся Moon Surface и Abstract Female Face Silhouette отдельной партией\n---\n\n# Пять STL: модели и лунные кратеры\n\nОпубликованы SEO title/meta description и20 новых JPEG1500×1000 в пяти собственных слайдерах. Исходные основные тексты сохранены дословно; H1/URL/excerpt/specs/commerce/prices/download files/верхние галереи и общие HTML-блоки сохранены.\n\n'+table
report+='\n## Проверка\n\nDB/SEO5/5, защищённые поля5/5; media20/20: MIMEimage/jpeg,1500×1000, original-byteSHA256, title/alt с AI-концептом, HTTP200. Public10/10: обычный и QA-query URL, title/meta/H1/self-canonical/indexability/Product schema/cart CTA/нет raw VC-shortcodes/только жирная центрованная AI-подпись. Browser40/40: четыре слайда каждого товара, desktop1440×1000/mobile390×844; один видимый загруженный слайд, стрелки2, точки4, Next/Previous/first-last dots10sets, autoplay=no/wrap=no, без horizontal overflow. Все10screens осмотрены.\n\nСохранены'+str(old)+' прежних верхних media; прежняя иллюстрация Sheikh15536 также существует (title/URL/fileSHA проверены). Для кратеров прежние sample renders и Internet ideas gallery сохранены, заменена только первая standalone illustration16705/16730. Старые media не удалялись. Всего20 оригинальных native ImageGen PNG, промпты и10 собственных SKU refs сохранены рядом с отчётом и в двух release-папках GitHub. Каждый результат осмотрен: desktop полностью на сплошной опоре, отдельные части закреплены; изображения являются концептами, а не mesh verification. Zombie wall/gift coral glasses описаны в alt; Troll сохраняет исходный stand.\n'
report+='\n## Источники и семантика\n\nGoogle, English, hl=en/gl=us/pws=0; фактическая локация Unknown. Сохранены7 запросов и full snapshots. Кластеры редакционные; частотности, позиции и US ranks не измерялись. Bust отделён от Mosque/другого Sheikh; Troll skull от плоского meme/physical/free; Zombie box от game organisers; lunar relief от Moon globe/Mars/free NASA/game terrain. Новые accuracy/readiness/license обещания не добавлены. Исходные размеры Sheikh76×48×68m и прежние production/research claims сохранены для отдельной валидации. Troll original non-commercial license сохранён; AI exhibition не предоставляет коммерческих прав. [[Page Briefs]], [[Intent Review]], [[Scope Correction]], [[../Next Lunar Sliders 2026-10-08/Page Briefs]].\n'
report+='\nПервоначальный отбор пропустил4 STL-icon товара; вывод о трёх оставшихся исправлен. Партия завершена пятью реальными STL-товарами. В свежем каталоге516 published products; необработанные подтверждённые STL: Moon Surface16743 и Abstract Female Face Silhouette16812. Belarus9512 исключён владельцем; Denmark9516 уже обработан по [[../Ten More Global STL Sliders 2026-10-07/Release Report]], повторно не менялся.\n'
report+='\n## GitHub и external runtime\n\nGitHub-first: origin SSH/main, fetch/prune, исходныйHEAD85b0692, upstream0:0; прежние unrelated dirty/untracked сохранены, staging ограничен двумя новыми release-папками. Source commits:\n\n'+''.join('- `'+d['commit']+'`, WP path`'+d['wp_source']+'`, archiveSHA256`'+d['archive_sha256']+'` совпал local/VPS; PHP lint и preview прошли, apply выполнен один раз.\n' for d in deploy)
report+='\nПромежуточный lunar source ceb6a125ca07c7c66c478df610ec59997585cf15 не публиковался: preview остановил неверный excerpt hash из-за locale-decoding NBSP. Фактические excerpts не менялись; исправлен явный UTF-8 decode, новый source a785368 прошёл preview. Публикация не повторяется после evidence commit.\n\nWireGuard SSH vpsadmin@10.66.66.1 и sudoDocker available. WP/DB running,restart0, StartedAt/port bindings before-after совпали: WP127.0.0.1:8083, DB безpublished ports. Без build/restart и без изменения local runtime. `runtime-before.txt`/`runtime-after.txt`, `deployment.json`, `preservation-qa.json`, `final-five-qa.json`, `catalog-audit.json`. P1 analytics/recovery/consent, index check10.10, yellow/degraded сохранены; другие проекты не проверялись.\n'
report+='\n## Backup и rollback\n\nСохранены исходные baseline, durable per-product WordPress options с before/after и media journal, экспорт backups рядом с каждой release-папкой. Rollback-preview3/3 и2/2 прошли после публикации. Откат выполняется отдельно для двух непересекающихся групп; старые и новые media сохраняются. Перед rollback снова выполнить соответствующий preview; он блокирует drift и защищает owner edits.\n\n```sh\nsudo -n docker exec shustrik-maps-wordpress-1 php /tmp/next-models-d2bf7c0/release.php --rollback-preview\nsudo -n docker exec shustrik-maps-wordpress-1 php /tmp/next-models-d2bf7c0/release.php --rollback\nsudo -n docker exec shustrik-maps-wordpress-1 php /tmp/next-lunar-a785368/release.php --rollback-preview\nsudo -n docker exec shustrik-maps-wordpress-1 php /tmp/next-lunar-a785368/release.php --rollback\n```\n\n`--apply` повторно не запускать. Если /tmp исчезнет, восстановить точный source archive из GitHub, сверитьSHA, затем preview. Option prefixes `_shustrik_next_models_stl_slider_backup_20261008_` и `_shustrik_next_lunar_stl_slider_backup_20261008_`; media journals с тем же scope.\n\n![Опубликованная карточка Troll Face](published-troll-skull-proof.png)\n'
(root/'Release Report.md').write_text(report,encoding='utf-8')
(lunar/'Release Report.md').write_text('# Copernicus и Theophilus — опубликовано и проверено\n\nПолный итог пяти товаров: [[../Next Model Sliders 2026-10-08/Release Report]]. Source a785368d7163127fd1927f5c7757156315a37a4b; apply один раз. DB2/2,media8/8,HTTP4/4,browser16/16,current rollback-preview2/2,protected/runtime unchanged. Исходные upper/gallery/sample renders/Internet ideas/HTML blocks сохранены. Промежуточный ceb6a12 не публиковался.\n',encoding='utf-8')
summary='## Пять STL: модели и кратеры — '+stamp+' МСК\n\nSheikh Zayed Bust, Troll Face Skull, Zombie Monster Storage Box, Copernicus Lunar Crater, Theophilus Lunar Crater: SEO title/meta и20JPEG опубликованы. DB5/5,media20/20,HTTP10/10,browser40/40 и rollback-preview3/3+2/2 прошли; исходные тексты/H1/URL/specs/commerce/files/верхние галереи/общие блоки и старые media сохранены. Sources d2bf7c04f0ad077ebc4280bc5248c355bb1e05fc и a785368d7163127fd1927f5c7757156315a37a4b pushed и доставлены точными архивами; apply по одной операции на непересекающуюся группу. Прежние unrelated dirty/untracked сохранены.\n\nОтбор исправлен по STL format icons: ещё необработаны Moon Surface16743 и Abstract Female Face Silhouette16812. Denmark уже завершён, Belarus исключён. Google English/USA parameters; реальнаялокацияUnknown, frequency/rank не измерены. SSH/sudoDocker available, WP/DB runtime unchanged, без build/restart. P1 analytics/recovery/consent,index10.10,yellow/degraded сохранены. [[Next Model Sliders 2026-10-08/Release Report]].\n\n'
for filename in ['Shustrik Maps SEO - Overview.md','Shustrik Maps SEO - Next Actions.md']:
 p=proj/filename;s=p.read_text(encoding='utf-8');pos=s.find('\n---',4)+4;assert pos>=7;s=s[:pos]+'\n\n'+summary+s[pos:].lstrip('\n')
 if 'Overview' in filename:s=re.sub(r'current_commit: .*','current_commit: '+deploy[-1]['commit'],s,count=1);s=re.sub(r'last_runtime_check: .*','last_runtime_check: '+stamp,s,count=1)
 p.write_text(s,encoding='utf-8')
runtime=vault/'04 Operations/Runtime Status.md';rs='## Targeted Shustrik Maps — Five Models/Lunar STL, '+stamp+' МСК\n\nExternal https://shustrik-maps.com; sources d2bf7c0/a785368, exact archives local/VPS matched. Пять карточек/20JPEG опубликованы, DB5/5,media20/20,HTTP10/10,browser40/40,current rollback-preview3/3+2/2 passed. Prose/commerce/files/H1/URL/верхние галереи/старые media/общие блоки сохранены. SSH WireGuard/sudoDocker available; WP/DB running/restart0/StartedAt/ports unchanged: WP127.0.0.1:8083,DB no published ports. No build/restart/local change. P1 analytics/recovery/consent,index10.10,yellow/degraded сохранены. Другие проекты этим адресным срезом не проверялись. [[01 Projects/WordPress/shustrik-maps.com/Next Model Sliders 2026-10-08/Release Report]].\n\n';runtime.write_text(rs+runtime.read_text(encoding='utf-8'),encoding='utf-8')
for part,folder in [(root,'next-model-slider-release-20261008'),(lunar,'next-lunar-slider-release-20261008')]:
 out=repo/folder
 for p in part.iterdir():
  if p.is_file() and p.suffix in ['.json','.md','.txt','.png','.py','.php'] and p.name not in ['prepare.py','export.py','release.php','snapshot.php','baseline.json','selection.json','manifest.json','generation-jobs.json','native-registry.json','media.json','visual-review.json','semantic-review.json','Page Briefs.md','Intent Review.md','intent-evidence.json','deliver.py','backup-export.php','refs-export.php','public-qa.py','verify-preservation.py'] and not p.name.startswith('google-'):shutil.copy2(p,out/p.name)
 for p in out.iterdir():
  if p.suffix in ['.json','.md','.txt','.py','.php']:p.write_text('\n'.join(x.rstrip() for x in p.read_text(encoding='utf-8-sig').splitlines()).rstrip()+'\n',encoding='utf-8',newline='\n')
print('Final5/5 report/documents/runtime saved; protected previous upper media',old,'remaining',[(r['id'],r['title']) for r in remaining])
