<?php
ini_set('display_errors','0');define('WP_USE_THEMES',false);ob_start();require '/var/www/html/wp-load.php';ob_end_clean();
function fail_restore($s){throw new RuntimeException($s);}
function state_restore($id){$p=get_post($id);return ['id'=>$id,'content'=>$p->post_content,'h1'=>$p->post_title,'excerpt'=>$p->post_excerpt,'url'=>get_permalink($id),'meta_hash'=>hash('sha256',serialize(get_post_meta($id))),'seo_title'=>get_post_meta($id,'_yoast_wpseo_title',true),'meta_description'=>get_post_meta($id,'_yoast_wpseo_metadesc',true)];}
function invariant_restore($a,$b){foreach(['h1','excerpt','url','meta_hash','seo_title','meta_description'] as $k)if($a[$k]!==$b[$k])fail_restore('Protected drift '.$a['id'].' '.$k);}
try{
 if(PHP_SAPI!=='cli'||rtrim(home_url(),'/')!=='https://shustrik-maps.com')fail_restore('Site');$mode=$argv[1]??'--preview';if(!in_array($mode,['--preview','--apply','--verify']))fail_restore('Mode');$key='_shustrik_stl_description_restore_20261006';$saved=get_option($key,null);$prepared=[];$out=[];
 foreach([9522,9520] as $id){$now=state_restore($id);
  if($mode==='--verify'){if(!$saved)fail_restore('Missing restore backup');$r=null;foreach($saved['rows'] as $row)if($row['before']['id']===$id)$r=$row;if(!$r)fail_restore('Scope');invariant_restore($r['before'],$now);if($now['content']!==$r['after_content'])fail_restore('Restored description drift');}
  else{if($saved!==null)fail_restore('Already applied; use verify');$release=get_option('_shustrik_stl_slider_backup_20261006_'.$id);if(!$release||$now['content']!==$release['after_content'])fail_restore('Published description drift '.$id);preg_match_all('/\[vc_column_text[^\]]*\](.*?)\[\/vc_column_text\]/s',$release['before']['content'],$original);if(count($original[1])<2)fail_restore('Original blocks missing');$i=0;$after=preg_replace_callback('/(\[vc_column_text[^\]]*\])(.*?)(\[\/vc_column_text\])/s',function($m)use(&$i,$original){$n=$i++;return $n<2?$m[1].$original[1][$n].$m[3]:$m[0];},$now['content']);if($i!==3)fail_restore('Unexpected description blocks');if(strpos($after,'AI-generated application concepts.')===false||substr_count($after,'[woodmart_gallery')!==1)fail_restore('Preserved visuals missing');$prepared[]=['before'=>$now,'after_content'=>$after];}
  $out[]=['id'=>$id,'url'=>$now['url'],'seo_title'=>$now['seo_title'],'meta_description'=>$now['meta_description'],'seo_and_all_product_meta_preserved'=>true,'slider_and_ai_notice_preserved'=>true];
 }
 if($mode==='--apply'){
  if(!add_option($key,['utc'=>gmdate('c'),'rows'=>$prepared],'',false))fail_restore('Backup exists');global $wpdb;$wpdb->query('START TRANSACTION');try{foreach($prepared as $r){$b=$r['before'];$id=$b['id'];$wpdb->get_var($wpdb->prepare("SELECT ID FROM {$wpdb->posts} WHERE ID=%d FOR UPDATE",$id));clean_post_cache($id);if(state_restore($id)!==$b)fail_restore('Concurrent edit '.$id);$n=$wpdb->query($wpdb->prepare("UPDATE {$wpdb->posts} SET post_content=%s,post_modified=%s,post_modified_gmt=%s WHERE ID=%d AND post_content=%s",$r['after_content'],current_time('mysql'),current_time('mysql',true),$id,$b['content']));if($n!==1)fail_restore('Write');clean_post_cache($id);$after=state_restore($id);invariant_restore($b,$after);if($after['content']!==$r['after_content'])fail_restore('Written body');}$wpdb->query('COMMIT');}catch(Throwable $e){$wpdb->query('ROLLBACK');foreach($prepared as $r)clean_post_cache($r['before']['id']);throw $e;}
  foreach($out as $r){if(function_exists('rocket_clean_files'))rocket_clean_files([$r['url']]);do_action('litespeed_purge_url',$r['url']);}
 }
 echo json_encode(['ok'=>true,'mode'=>$mode,'utc'=>gmdate('c'),'rows'=>$out,'backup_option'=>$key],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";
}catch(Throwable $e){echo json_encode(['ok'=>false,'reason'=>$e instanceof RuntimeException?$e->getMessage():'Internal error'])."\n";exit(1);}
